import Foundation // Needed for Codable conformance for classes

/// A type alias for the unique identifier of a `DescriptionHandler`.
public typealias DescriptionHandlerID = String

/// A type alias for the unique identifier of a `RoomActionHandler`.
public typealias RoomActionHandlerID = String

/// Represents a location (room) within the game world.
public struct Location: Codable, Identifiable, Equatable, Sendable {
    // --- Stored Properties (Alphabetical) ---

    /// A dynamic description generated by a registered handler.
    public var descriptionHandlerID: DescriptionHandlerID? = nil

    /// Storage for state values and flags, potentially with associated dynamic behavior
    /// defined externally.
    ///
    /// Use this for mutable state (e.g., description text) and inherent boolean flags
    /// (e.g., is it inherently lit, visited, etc.). Values are keyed by `PropertyID`.
    ///
    /// Access and modification should typically go through `GameEngine` helper methods
    /// or convenience accessors like `flag(_:)`.
    ///
    /// Values are typically represented using the `StateValue` enum.
    public var dynamicValues: [PropertyID: StateValue]

    /// Defines the connections (exits) from this location to others.
    public var exits: [Direction: Exit]

    /// Items that are considered "global" to this location and always in scope,
    /// regardless of light level (e.g., the location object itself, fixed scenery).
    public var globals: [ItemID]

    /// The unique identifier for this location.
    public let id: LocationID

    /// The display name of the location.
    public var name: String

    /// Optional ID for a room-specific action handler.
    public var roomActionHandlerID: RoomActionHandlerID? = nil

    // MARK: - Initializer

    public init(
        id: LocationID,
        name: String,
        description: String, // Standard static description
        exits: [Direction: Exit] = [:],
        descriptionHandlerID: DescriptionHandlerID? = nil,
        roomActionHandlerID: RoomActionHandlerID? = nil,
        globals: ItemID...,
        dynamicValues: [PropertyID: StateValue] = [:],

        // Common Flags (Migrated from LocationProperty)
        inherentlyLit: Bool = false,
        isLit: Bool = false, // Typically managed by engine
        noMagic: Bool = false,
        isOutside: Bool = false,
        isSacred: Bool = false,
        descriptionChanged: Bool = false,
        isLand: Bool = true, // Default to land
        visited: Bool = false,
        isWater: Bool = false
    ) {
        self.id = id
        self.name = name
        self.exits = exits
        self.globals = globals
        self.descriptionHandlerID = descriptionHandlerID
        self.roomActionHandlerID = roomActionHandlerID

        // Initialize dynamic values from parameters and flags
        var initialValues = dynamicValues
        initialValues[.description] = .string(description)

        // Set boolean flags
        if inherentlyLit { initialValues[.inherentlyLit] = .bool(true) }
        if isLit { initialValues[.locationIsLit] = .bool(true) }
        if noMagic { initialValues[.breaksMagic] = .bool(true) }
        if isOutside { initialValues[.isOutside] = .bool(true) }
        if isSacred { initialValues[.isSacred] = .bool(true) }
        if descriptionChanged { initialValues[.isChanged] = .bool(true) }
        if isLand { initialValues[.isLand] = .bool(true) } else { initialValues[.isLand] = .bool(false) }
        if visited { initialValues[.isVisited] = .bool(true) }
        if isWater { initialValues[.isWater] = .bool(true) }

        self.dynamicValues = initialValues
    }

    // MARK: - Codable Conformance

    private enum CodingKeys: String, CodingKey {
        // Removed 'properties', added 'dynamicValues'
        case id, name, exits, globals, descriptionHandlerID, roomActionHandlerID, dynamicValues
    }

    // init(from:) and encode(to:) need to handle dynamicValues
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decode(LocationID.self, forKey: .id)
        name = try container.decode(String.self, forKey: .name)
        exits = try container.decode([Direction: Exit].self, forKey: .exits)
        globals = try container.decode([ItemID].self, forKey: .globals)
        descriptionHandlerID = try container.decodeIfPresent(DescriptionHandlerID.self, forKey: .descriptionHandlerID)
        roomActionHandlerID = try container.decodeIfPresent(RoomActionHandlerID.self, forKey: .roomActionHandlerID)
        // Handle potentially missing dynamicValues for backward compatibility if needed
        dynamicValues = try container.decodeIfPresent([PropertyID: StateValue].self, forKey: .dynamicValues) ?? [:]

        // Ensure longDescription exists if migrating from old format without dynamicValues
        if dynamicValues[.description] == nil {
            // Attempt to recover from potential older format (this might need adjustment based on actual old structure)
            // If there was a separate 'description' field, we might try decoding that.
            // For now, default to empty if missing entirely.
            // TODO: Verify migration strategy from older saves if necessary.
            dynamicValues[.description] = .string("") // Default or try decoding old field
            print("Warning: Migrating Location \(id) with potentially missing longDescription in dynamicValues.")
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(exits, forKey: .exits)
        try container.encode(globals, forKey: .globals)
        try container.encodeIfPresent(descriptionHandlerID, forKey: .descriptionHandlerID)
        try container.encodeIfPresent(roomActionHandlerID, forKey: .roomActionHandlerID)
        try container.encode(dynamicValues, forKey: .dynamicValues)
    }

    // MARK: - Convenience Accessors

    /// Checks if a boolean flag is set in the location's `dynamicValues`.
    /// - Parameter id: The `PropertyID` of the flag to check.
    /// - Returns: `true` if the flag exists and is set to `true`, `false` otherwise.
    public func flag(_ id: PropertyID) -> Bool {
        dynamicValues[id] == .bool(true)
    }
}

// MARK: - Comparable Conformance

extension Location: Comparable {
    public static func < (lhs: Location, rhs: Location) -> Bool {
        lhs.id < rhs.id
    }
}

// MARK: - Equatable Conformance

// Equatable conformance should still be synthesized correctly
