import Foundation

/// Handles the "EXAMINE" command and its synonyms (e.g., "LOOK AT", "DESCRIBE"), providing
/// a detailed description of a specified item or the player.
public struct ExamineActionHandler: ActionHandler {
    /// Validates the "EXAMINE" command.
    ///
    /// This method ensures that:
    /// 1. A direct object is specified (the player must indicate *what* to examine).
    /// 2. If the direct object is an item, it must exist and be reachable by the player.
    /// 3. Examining the player ("EXAMINE SELF") is also permitted.
    ///
    /// - Parameter context: The `ActionContext` for the current action.
    /// - Throws: `ActionResponse.custom` if no direct object is provided,
    ///           `ActionResponse.unknownEntity` if an item direct object does not exist,
    ///           `ActionResponse.itemNotAccessible` if an item cannot be reached, or
    ///           `ActionResponse.prerequisiteNotMet` if trying to examine something other
    ///           than an item or the player.
    public func validate(context: ActionContext) async throws {
        // For ALL commands, allow empty directObjects (handled in process method)
        if context.command.isAllCommand {
            return
        }

        // 1. Ensure we have at least one direct object for non-ALL commands
        guard !context.command.directObjects.isEmpty else {
            throw ActionResponse.custom(context.message(.examineWhat))
        }

        // For single object commands, validate the single object
        guard let directObjectRef = context.command.directObject else {
            throw ActionResponse.custom(context.message(.examineWhat))
        }

        switch directObjectRef {
        case .item(let targetItemID):
            // 2. Check if item exists
            guard (try? await context.engine.item(targetItemID)) != nil else {
                throw ActionResponse.unknownEntity(directObjectRef)
            }
            // 3. Check reachability
            guard await context.engine.playerCanReach(targetItemID) else {
                throw ActionResponse.itemNotAccessible(targetItemID)
            }
        case .player:
            // Allow examining self
            return
        default:
            let message = context.message(.canOnlyActOnItems(verb: "examine"))
            throw ActionResponse.prerequisiteNotMet(message)
        }
    }

    /// Processes the "EXAMINE" command.
    ///
    /// - If the direct object is the player ("EXAMINE SELF"), a standard message is returned.
    /// - If the direct object is an item (validation ensures it exists and is reachable):
    ///   1. The item is marked with the `.isTouched` flag (unless it's the "self" item).
    ///   2. Pronouns are updated to refer to this item (unless it's the "self" item).
    ///   3. A description is generated with the following priority:
    ///      a. If the item `.isReadable` and has non-empty `.readText`, that text is shown.
    ///      b. If the item `.isContainer` or `.isDoor`, a description including its contents
    ///         (if open/transparent) or closed state is generated by `describeContainerOrDoor()`.
    ///      c. If the item `.isSurface`, a description including items on it is generated by
    ///         `describeSurface()`.
    ///      d. Otherwise, the item's standard dynamic long description is fetched.
    ///   4. An `ActionResult` is returned with the generated message and any state changes.
    ///
    /// For ALL commands, processes each object individually and provides consolidated feedback.
    ///
    /// - Parameter context: The `ActionContext` for the current action.
    /// - Returns: An `ActionResult` containing the detailed description and any relevant state changes.
    /// - Throws: Can throw errors from engine calls if issues occur (e.g., item not found during processing).
    public func process(context: ActionContext) async throws -> ActionResult {
        // Check for EXAMINE IN/ON preposition variants - delegate to look-inside behavior
        if context.command.preposition == "in" || context.command.preposition == "on" {
            let lookInsideHandler = LookInsideActionHandler()
            return try await lookInsideHandler.process(context: context)
        }

        // For ALL commands, empty directObjects is valid (means nothing to examine)
        if !context.command.isAllCommand {
            guard !context.command.directObjects.isEmpty else {
                return ActionResult(context.message(.canOnlyActOnItems(verb: "examine")))
            }
        }

        var allStateChanges: [StateChange] = []
        var messages: [String] = []
        var examinedItems: [Item] = []

        // Process each object individually
        for directObjectRef in context.command.directObjects {
            switch directObjectRef {
            case .item(let targetItemID):
                do {
                    let targetItem = try await context.engine.item(targetItemID)

                    // Validate this specific item for ALL commands
                    if context.command.isAllCommand {
                        // Check if player can reach the item
                        guard await context.engine.playerCanReach(targetItemID) else {
                            continue  // Skip unreachable items in ALL commands
                        }
                    }

                    var itemStateChanges: [StateChange] = []

                    // Special case: examining 'self' as an item should not record any state changes
                    if targetItem.id != "self" {
                        // --- State Change: Mark as Touched ---
                        if let update = await context.engine.setFlag(.isTouched, on: targetItem) {
                            itemStateChanges.append(update)
                        }
                        // Note: Pronoun updates are handled after processing all items
                    }

                    // --- Determine Message ---
                    var itemMessages = [String]()

                    // Priority 1: Readable Text (Check dynamic value)
                    if targetItem.hasFlag(.isReadable),
                        let readText: String = try? await context.engine.attribute(
                            .readText, of: targetItem.id),
                        !readText.isEmpty
                    {
                        itemMessages.append(readText)
                    }

                    // Smart handling for items that are both containers and surfaces
                    if targetItem.hasFlag(.isContainer) && targetItem.hasFlag(.isSurface) {
                        // Check if surface items have meaningful firstDescriptions
                        let contents = await context.engine.items(in: .item(targetItem.id))
                        let hasFirstDescriptions = contents.contains { item in
                            if let firstDescription = item.attributes[.firstDescription],
                                case .string(let description) = firstDescription,
                                !description.isEmpty
                            {
                                return true
                            }
                            return false
                        }

                        if hasFirstDescriptions {
                            // Use surface description (which includes container info when needed)
                            try itemMessages.append(
                                await describeSurface(
                                    targetItem: targetItem,
                                    engine: context.engine
                                )
                            )
                        } else {
                            // Use container description
                            try itemMessages.append(
                                await describeContainerOrDoor(
                                    targetItem: targetItem,
                                    engine: context.engine
                                )
                            )
                        }
                    }
                    // Priority 2: Container/Door Description (only if not also surface)
                    else if targetItem.hasFlag(.isContainer) || targetItem.hasFlag(.isDoor) {
                        try itemMessages.append(
                            await describeContainerOrDoor(
                                targetItem: targetItem,
                                engine: context.engine
                            )
                        )
                    }
                    // Priority 3: Surface Description (only if not also container)
                    else if targetItem.hasFlag(.isSurface) {
                        try itemMessages.append(
                            await describeSurface(
                                targetItem: targetItem,
                                engine: context.engine
                            )
                        )
                    }
                    // Priority 4: Dynamic Long Description
                    else {
                        // Use the registry to generate the description using the item ID and key
                        let (description, _, _) = try await context.engine
                            .generateDescriptionWithSourceInfo(
                                for: targetItem.id,
                                attributeID: .description
                            )
                        // Always add the description for simple items, even if it's the default
                        // The "nothing special" filtering only applies to containers/surfaces that have additional info
                        itemMessages.append(description)
                    }

                    let message = itemMessages.joined(separator: " ")

                    allStateChanges.append(contentsOf: itemStateChanges)
                    examinedItems.append(targetItem)

                    // For multiple objects, prefix with item name
                    if context.command.isAllCommand || context.command.directObjects.count > 1 {
                        messages.append("- \(targetItem.name.capitalizedFirst): \(message)")
                    } else {
                        messages.append(message)
                    }

                } catch {
                    // For ALL commands, skip items that cause errors
                    if !context.command.isAllCommand {
                        throw error
                    }
                }

            case .player:
                // Classic Zork response for EXAMINE SELF
                if context.command.isAllCommand || context.command.directObjects.count > 1 {
                    messages.append("- Yourself: \(context.message(.examineYourself))")
                } else {
                    messages.append(context.message(.examineYourself))
                }

            default:
                // For ALL commands, skip non-items
                if !context.command.isAllCommand {
                    return ActionResult(context.message(.canOnlyActOnItems(verb: "examine")))
                }
            }
        }

        // Update pronouns appropriately for multiple objects
        if !examinedItems.isEmpty {
            let lastItem = examinedItems.last!
            if examinedItems.count > 1 {
                // For multiple items, update both "it" and "them"
                let pronounChanges = await context.engine.updatePronounsForMultipleObjects(
                    lastItem: lastItem,
                    allItems: examinedItems
                )
                allStateChanges.append(contentsOf: pronounChanges)
            } else {
                // For single item, use the original method
                if let pronounChange = await context.engine.updatePronouns(to: lastItem) {
                    allStateChanges.append(pronounChange)
                }
            }
        }

        // Generate appropriate message
        let finalMessage: String
        if context.command.isAllCommand {
            if examinedItems.isEmpty && messages.isEmpty {
                finalMessage = context.message(.nothingHereToExamine)
            } else {
                finalMessage = messages.joined(separator: "\n")
            }
        } else {
            finalMessage = messages.joined(separator: "\n")
        }

        return ActionResult(
            message: finalMessage,
            changes: allStateChanges
        )
    }

    // MARK: - Private Helpers (Adapted to return String)

    /// Generates a description for an item that is a container or a door.
    ///
    /// The description includes the item's base description followed by information about
    /// its contents (if open or transparent) or its closed state.
    ///
    /// - Parameters:
    ///   - targetItem: The container or door `Item` to describe.
    ///   - engine: The `GameEngine` instance for accessing item state and utility functions.
    /// - Returns: A string describing the container or door and its state/contents.
    /// - Throws: Errors if fetching dynamic properties like `.isOpen` fails.
    private func describeContainerOrDoor(
        targetItem: Item,
        engine: GameEngine
    ) async throws -> String {
        var descriptionParts: [String] = []

        // Start with the item's main description, using the registry with ID and key
        let (baseDescription, wasComputed, isDefault) =
            try await engine.generateDescriptionWithSourceInfo(
                for: targetItem.id,
                attributeID: .description
            )

        // Only add the base description if it's not a default "nothing special" message
        if !isDefault {
            descriptionParts.append(baseDescription)
        }

        // If a compute handler provided the description, it's complete - don't add more
        guard !wasComputed else {
            return baseDescription
        }

        // Check dynamic property for open state
        let isOpen = try await engine.hasFlag(.isOpen, on: targetItem.id)
        let isTransparent = targetItem.hasFlag(.isTransparent)

        if isOpen || isTransparent {
            let contents = await engine.items(in: .item(targetItem.id))
            if contents.isEmpty {
                descriptionParts.append("The \(targetItem.name) is empty.")
            } else {
                let itemNames = contents.listWithIndefiniteArticles
                descriptionParts.append("The \(targetItem.name) contains \(itemNames).")
            }
        } else {
            descriptionParts.append("The \(targetItem.name) is closed.")
        }

        // If we have no meaningful description parts, fall back to the base description
        if descriptionParts.isEmpty {
            descriptionParts.append(baseDescription)
        }

        return descriptionParts.joined(separator: " ")
    }

    /// Generates a description for an item that is a surface.
    ///
    /// The description includes the item's base description followed by a list of any items
    /// currently on its surface.
    ///
    /// - Parameters:
    ///   - targetItem: The surface `Item` to describe.
    ///   - engine: The `GameEngine` instance for accessing item state and utility functions.
    /// - Returns: A string describing the surface and any items on it.
    private func describeSurface(targetItem: Item, engine: GameEngine) async throws -> String {
        // Check if a compute handler provided a custom description
        let (baseDescription, wasComputed, isDefault) =
            try await engine.generateDescriptionWithSourceInfo(
                for: targetItem.id,
                attributeID: .description
            )

        // If a compute handler provided the description, it's complete - don't add more
        guard !wasComputed else {
            return baseDescription
        }

        // Get items on the surface
        let contents = await engine.items(in: .item(targetItem.id))

        if contents.isEmpty {
            // No items on surface, return base description
            return baseDescription
        }

        // Analyze items to determine description strategy
        var itemsWithFirstDescription: [Item] = []
        var itemsWithoutFirstDescription: [Item] = []
        var allFirstDescriptionsEstablishContext = true

        for item in contents {
            if let firstDescription = item.attributes[.firstDescription],
                case .string(let description) = firstDescription,
                !description.isEmpty
            {
                itemsWithFirstDescription.append(item)

                // Check if firstDescription mentions the parent surface (smart context detection)
                let parentKeywords = [targetItem.name.lowercased(), "table", "surface", "on the"]
                let establishesContext = parentKeywords.contains(where: {
                    description.lowercased().contains($0)
                })

                // If any firstDescription doesn't establish context, we can't rely on them alone
                if !establishesContext {
                    allFirstDescriptionsEstablishContext = false
                }
            } else {
                itemsWithoutFirstDescription.append(item)
                // If any item lacks firstDescription, we can't rely on firstDescriptions alone
                allFirstDescriptionsEstablishContext = false
            }
        }

        // Strategy 1: All items have contextual firstDescriptions - use only those
        if itemsWithoutFirstDescription.isEmpty && allFirstDescriptionsEstablishContext {
            var descriptionLines: [String] = []

            for item in itemsWithFirstDescription.sorted() {
                if let firstDescription = item.attributes[.firstDescription],
                    case .string(let description) = firstDescription
                {
                    descriptionLines.append(description)
                }

                // Add container contents if applicable
                if item.hasFlag(.isContainer) {
                    let isOpen = item.hasFlag(.isOpen)
                    let isTransparent = item.hasFlag(.isTransparent)

                    if isOpen || isTransparent {
                        let containerContents = await engine.items(in: .item(item.id))
                        if !containerContents.isEmpty {
                            descriptionLines.append(
                                """
                                The \(item.name) contains \
                                \(containerContents.sorted().listWithIndefiniteArticles).
                                """)
                        }
                    }
                }
            }

            return descriptionLines.joined(separator: " ")
        }

        // Strategy 2: Mixed items or non-contextual firstDescriptions - combine approaches
        else if !itemsWithFirstDescription.isEmpty {
            var descriptionParts: [String] = []

            // Include base description only if items don't establish full context
            if !allFirstDescriptionsEstablishContext && !isDefault {
                descriptionParts.append(baseDescription)
            }

            // Add items without firstDescription as a combined listing
            if !itemsWithoutFirstDescription.isEmpty {
                let surfaceItemsList = itemsWithoutFirstDescription.sorted()
                    .listWithIndefiniteArticles
                let isAre = itemsWithoutFirstDescription.count == 1 ? "is" : "are"
                descriptionParts.append("On the \(targetItem.name) \(isAre) \(surfaceItemsList).")
            }

            // Add individual firstDescriptions
            for item in itemsWithFirstDescription.sorted() {
                if let firstDescription = item.attributes[.firstDescription],
                    case .string(let description) = firstDescription
                {
                    descriptionParts.append(description)
                }

                // Add container contents if applicable
                if item.hasFlag(.isContainer) {
                    let isOpen = item.hasFlag(.isOpen)
                    let isTransparent = item.hasFlag(.isTransparent)

                    if isOpen || isTransparent {
                        let containerContents = await engine.items(in: .item(item.id))
                        if !containerContents.isEmpty {
                            descriptionParts.append(
                                """
                                The \(item.name) contains \
                                \(containerContents.sorted().listWithIndefiniteArticles).
                                """)
                        }
                    }
                }
            }

            return descriptionParts.joined(separator: " ")
        }

        // Strategy 3: No firstDescriptions - use traditional surface description
        else {
            var descriptionParts: [String] = []

            // Add base description only if it's not the generic default message
            if !baseDescription.isEmpty && !isDefault {
                descriptionParts.append(baseDescription)
            }

            // Add surface contents as a single combined sentence
            let sortedContents = contents.sorted()
            let surfaceItemsList = sortedContents.listWithIndefiniteArticles
            let isAre = sortedContents.count == 1 ? "is" : "are"
            descriptionParts.append("On the \(targetItem.name) \(isAre) \(surfaceItemsList).")

            return descriptionParts.joined(separator: " ")
        }
    }
}
