import Foundation

/// Handles the "LOOK" command and its synonyms (e.g., "L"). It can also implicitly handle
/// "EXAMINE [ITEM]" logic if a direct object is provided with the LOOK command.
///
/// - When used without a direct object ("LOOK"), it describes the player's current location,
///   including its name, description, and any visible items.
/// - When used with a direct object that is an item ("LOOK [ITEM]" or "EXAMINE [ITEM]"),
///   it describes the specified item, including its contents if it's an open/transparent
///   container or a surface.
public struct LookActionHandler: ActionHandler {
    /// Validates the "LOOK" command.
    ///
    /// - If no direct object is provided, validation always succeeds.
    /// - If a direct object is provided:
    ///   1. It must refer to an item.
    ///   2. The item must exist.
    ///   3. The player must be able to reach the item.
    ///
    /// - Parameter context: The `ActionContext` for the current action.
    /// - Throws: `ActionResponse.prerequisiteNotMet` if the direct object is not an item,
    ///           `ActionResponse.unknownEntity` if the item does not exist, or
    ///           `ActionResponse.itemNotAccessible` if the item cannot be reached.
    public func validate(context: ActionContext) async throws {
        // LOOK (no direct object) always validates.
        guard let directObjectRef = context.command.directObject else {
            return
        }

        // If a direct object is present, it must be an item for LOOK/EXAMINE.
        guard case .item(let targetItemID) = directObjectRef else {
            // For now, only items are supported when a direct object is specified.
            throw ActionResponse.prerequisiteNotMet("You can only look at items this way.")
        }

        // EXAMINE [Item] - Ensure item exists and is reachable
        guard (try? await context.engine.item(targetItemID)) != nil else {
            throw ActionResponse.unknownEntity(directObjectRef) // Was unknownItem
        }

        // Check reachability using ScopeResolver
        guard await context.engine.playerCanReach(targetItemID) else {
            // Use a standard message even if item technically exists elsewhere
            throw ActionResponse.itemNotAccessible(targetItemID)
        }
    }

    /// Processes the "LOOK" command.
    ///
    /// - **LOOK (no direct object):**
    ///   1. Checks if the current location is dark. If so, prints the standard "pitch black" message.
    ///   2. Otherwise, prints the location's name and then its detailed description (generated by
    ///      `locationDescription(engine:showVerbose:stateSnapshot:)`).
    ///
    /// - **LOOK [ITEM] (or EXAMINE [ITEM]):**
    ///   1. Retrieves the target item (validation ensures it exists and is reachable).
    ///   2. Generates the item's base description using `engine.generateDescription()`.
    ///   3. Appends a description of its contents if it's a container or surface, using
    ///      `describeContents(of:engine:stateSnapshot:)`.
    ///   4. Creates a `StateChange` to set the `.isTouched` flag on the item.
    ///   5. Updates pronouns to refer to the item.
    ///   6. Returns an `ActionResult` with the combined description and state changes.
    ///
    /// - **LOOK THROUGH [ITEM]:**
    ///   Delegates to look-through behavior implemented in LookThroughActionHandler.
    ///
    /// - **LOOK IN/INSIDE/WITH [ITEM]:**
    ///   Delegates to look-inside behavior implemented in LookInsideActionHandler.
    ///
    /// - Parameter context: The `ActionContext` for the current action.
    /// - Returns: An `ActionResult` containing the description and any relevant `StateChange`s.
    /// - Throws: `ActionResponse.internalEngineError` or errors from engine calls if issues occur.
    public func process(context: ActionContext) async throws -> ActionResult {
        // Check if this is LOOK (no direct object) or LOOK AT [object] or LOOK THROUGH [object]
        if context.command.directObject == nil {
            // LOOK (no direct object) - describe the room
            // 1. Check for darkness FIRST
            guard await context.engine.playerLocationIsLit() else {
                return ActionResult("It is pitch black. You can't see a thing.")
            }

            await context.engine.ioHandler.print(
                "--- \(try context.engine.playerLocation().name) ---",
                style: .strong
            )

            // 2. Location is lit, proceed with description
            return ActionResult(
                await locationDescription(
                    try context.engine.playerLocation(),
                    engine: context.engine,
                    showVerbose: true,
                    stateSnapshot: context.stateSnapshot
                )
            )
        } else if context.command.preposition == "through" {
            // LOOK THROUGH [Object] - delegate to examine behavior for basic look-through functionality
            // Specific items can override this via ItemEventHandlers (like the kitchen window)
            let examineHandler = ExamineActionHandler()
            return try await examineHandler.process(context: context)
        } else if context.command.preposition == "in" ||
                  context.command.preposition == "inside" ||
                  context.command.preposition == "with" {
            // LOOK IN/INSIDE/WITH [Object] - delegate to look-inside behavior
            let lookInsideHandler = LookInsideActionHandler()
            return try await lookInsideHandler.process(context: context)
        } else {
            // LOOK AT [Object] - delegate to ExamineActionHandler to avoid code duplication
            let examineHandler = ExamineActionHandler()
            return try await examineHandler.process(context: context)
        }
    }

    // Default postProcess will print the message from ActionResult

    // MARK: - Helper Functions

    /// Generates a comprehensive description of the specified location, including its standard
    /// description and a list of any visible items.
    ///
    /// - Parameters:
    ///   - location: The `Location` to describe.
    ///   - engine: The `GameEngine` instance, used for description generation and scope resolution.
    ///   - showVerbose: A flag (currently unused but planned) that might control the level of detail.
    ///   - stateSnapshot: The `GameState` snapshot, used to retrieve item details.
    /// - Returns: A string containing the full description of the location and its visible items.
    private func locationDescription(
        _ location: Location,
        engine: GameEngine,
        showVerbose: Bool,
        stateSnapshot: GameState
    ) async -> String {
        var description: [String] = [
            await engine.generateDescription(
                for: location.id,
                attributeID: .description,
                engine: engine
            )
        ]

        // Use the correct ScopeResolver method
        let visibleItemIDs = await engine.scopeResolver.visibleItemsIn(locationID: location.id)

        // Filter out the player if present in scope (shouldn't happen normally)
        // let itemIDsToDescribe = visibleItemIDs.filter { $0 != .player }

        // guard !itemIDsToDescribe.isEmpty else { return } // Exit if no items to list

        // Original implementation using sentence format: - RESTORE THIS

        let visibleItems = visibleItemIDs.compactMap { stateSnapshot.items[$0] }

        if !visibleItems.isEmpty {
            let itemListing = visibleItems.listWithIndefiniteArticles
            description.append(
                "There \(visibleItems.count == 1 ? "is" : "are") \(itemListing) here."
            )
        }

        return description.joined(separator: "\n")
    }
}
