import Foundation

/// Handles the "LOOK" command and its synonyms (e.g., "L"). It can also implicitly handle
/// "EXAMINE [ITEM]" logic if a direct object is provided with the LOOK command.
///
/// - When used without a direct object ("LOOK"), it describes the player's current location,
///   including its name, description, and any visible items.
/// - When used with a direct object that is an item ("LOOK [ITEM]" or "EXAMINE [ITEM]"),
///   it describes the specified item, including its contents if it's an open/transparent
///   container or a surface.
public struct LookActionHandler: ActionHandler {
    // MARK: - Verb Definition Properties

    public let verbID: VerbID = .look

    public let syntax: [SyntaxRule] = [
        .match(.verb),
        .match(.verb, .directObject),
        .match(.verb, .at, .directObject),
//        .match(.verb, .through, .directObject),
    ]

    public let synonyms: [String] = ["l"]

    public let requiresLight: Bool = false

    // MARK: - Action Processing Methods
    /// Validates the "LOOK" command.
    ///
    /// - If no direct object is provided, validation always succeeds.
    /// - If a direct object is provided:
    ///   1. It must refer to an item.
    ///   2. The item must exist.
    ///   3. The player must be able to reach the item.
    ///
    /// - Parameter context: The `ActionContext` for the current action.
    /// - Throws: `ActionResponse.prerequisiteNotMet` if the direct object is not an item,
    ///           `ActionResponse.unknownEntity` if the item does not exist, or
    ///           `ActionResponse.itemNotAccessible` if the item cannot be reached.
    public func validate(context: ActionContext) async throws {
        // LOOK (no direct object) always validates.
        guard let directObjectRef = context.command.directObject else {
            return
        }

        // If a direct object is present, it must be an item for LOOK/EXAMINE.
        guard case .item(let targetItemID) = directObjectRef else {
            // For now, only items are supported when a direct object is specified.
            throw ActionResponse.prerequisiteNotMet(
                context.message.canOnlyLookAtItems()
            )
        }

        // EXAMINE [Item] - Ensure item exists and is reachable
        guard (try? await context.engine.item(targetItemID)) != nil else {
            throw ActionResponse.unknownEntity(directObjectRef)  // Was unknownItem
        }

        // Check reachability using ScopeResolver
        guard await context.engine.playerCanReach(targetItemID) else {
            // Use a standard message even if item technically exists elsewhere
            throw ActionResponse.itemNotAccessible(targetItemID)
        }
    }

    /// Processes the "LOOK" command.
    ///
    /// - **LOOK (no direct object):**
    ///   1. Checks if the current location is dark. If so, prints the standard "pitch black" message.
    ///   2. Otherwise, prints the location's name and then its detailed description (generated by
    ///      `locationDescription(engine:showVerbose:stateSnapshot:)`).
    ///
    /// - **LOOK [ITEM] (or EXAMINE [ITEM]):**
    ///   1. Retrieves the target item (validation ensures it exists and is reachable).
    ///   2. Generates the item's base description using `engine.generateDescription()`.
    ///   3. Appends a description of its contents if it's a container or surface, using
    ///      `describeContents(of:engine:stateSnapshot:)`.
    ///   4. Creates a `StateChange` to set the `.isTouched` flag on the item.
    ///   5. Updates pronouns to refer to the item.
    ///   6. Returns an `ActionResult` with the combined description and state changes.
    ///
    /// - **LOOK THROUGH [ITEM]:**
    ///   Delegates to look-through behavior implemented in LookThroughActionHandler.
    ///
    /// - **LOOK IN/INSIDE/WITH [ITEM]:**
    ///   Delegates to look-inside behavior implemented in LookInsideActionHandler.
    ///
    /// - Parameter context: The `ActionContext` for the current action.
    /// - Returns: An `ActionResult` containing the description and any relevant `StateChange`s.
    /// - Throws: `ActionResponse.internalEngineError` or errors from engine calls if issues occur.
    public func process(context: ActionContext) async throws -> ActionResult {
        // Check if this is LOOK (no direct object) or LOOK AT [object] or LOOK THROUGH [object]
        if context.command.directObject == nil {
            // LOOK (no direct object) - describe the room
            // Check for darkness FIRST
            guard await context.engine.playerLocationIsLit() else {
                return ActionResult(context.message.roomIsDark())
            }

            await context.engine.ioHandler.print(
                "--- \(try context.engine.playerLocation().name) ---",
                style: .strong
            )

            // Location is lit, proceed with description
            return ActionResult(
                await locationDescription(
                    try context.engine.playerLocation(),
                    engine: context.engine,
                    showVerbose: true
                )
            )
        } else if context.command.preposition == "through" {
            // LOOK THROUGH [Object] - delegate to examine behavior for basic look-through functionality
            // Specific items can override this via ItemEventHandlers (like the kitchen window)
            let examineHandler = ExamineActionHandler()
            return try await examineHandler.process(context: context)
        } else if context.command.preposition == "in" || context.command.preposition == "inside"
            || context.command.preposition == "with"
        {
            // LOOK IN/INSIDE/WITH [Object] - delegate to look-inside behavior
            let lookInsideHandler = LookInsideActionHandler()
            return try await lookInsideHandler.process(context: context)
        } else {
            // LOOK AT [Object] - delegate to ExamineActionHandler to avoid code duplication
            let examineHandler = ExamineActionHandler()
            return try await examineHandler.process(context: context)
        }
    }

    // Default postProcess will print the message from ActionResult

    // MARK: - Helper Functions

    /// Generates a comprehensive description of the specified location, including its standard
    /// description and a list of any visible items.
    ///
    /// - Parameters:
    ///   - location: The `Location` to describe.
    ///   - engine: The `GameEngine` instance, used for description generation and scope resolution.
    ///   - showVerbose: A flag (currently unused but planned) that might control the level of detail.
    ///   - stateSnapshot: The `GameState` snapshot, used to retrieve item details.
    /// - Returns: A string containing the full description of the location and its visible items.
    private func locationDescription(
        _ location: Location,
        engine: GameEngine,
        showVerbose: Bool
    ) async -> String {
        var description: [String] = [
            await engine.generateDescription(
                for: location.id,
                attributeID: .description,
                engine: engine
            )
        ]

        let stateSnapshot = await engine.gameState

        // Use the correct ScopeResolver method
        let visibleItemIDs = await engine.scopeResolver.visibleItemsIn(locationID: location.id)

        // Filter out the player if present in scope (shouldn't happen normally)
        // let itemIDsToDescribe = visibleItemIDs.filter { $0 != .player }

        // guard !itemIDsToDescribe.isEmpty else { return } // Exit if no items to list

        // Original implementation using sentence format: - RESTORE THIS

        let visibleItems = visibleItemIDs.compactMap { stateSnapshot.items[$0] }

        // Collect all items to describe: directly in location + items on surfaces/in open containers
        var allItemsToDescribe: [Item] = []
        var surfaceFirstDescriptions: [String] = []

        // Add items directly in the location
        allItemsToDescribe.append(contentsOf: visibleItems)

        // Check for surfaces and open/transparent containers in the location
        // Include ALL items in location (even those with .omitDescription) to check for surfaces
        let allItemsInLocation = stateSnapshot.items.values.filter {
            $0.parent == .location(location.id)
        }
        for item in allItemsInLocation {
            if item.hasFlag(.isSurface)
                || (item.hasFlag(.isContainer)
                    && (item.hasFlag(.isOpen) || item.hasFlag(.isTransparent)))
            {
                let contents = stateSnapshot.items(in: .item(item.id))

                // Check if any items on this surface have first descriptions
                let hasFirstDescriptions = contents.contains { item in
                    guard
                        let firstDescription = item.attributes[.firstDescription],
                        case .string(let description) = firstDescription,
                        !description.isEmpty
                    else {
                        return false
                    }
                    return !item.hasFlag(.isTouched)
                }

                if hasFirstDescriptions {
                    // Use individual first descriptions for items on surfaces
                    for contentItem in contents.sorted() {
                        if let firstDescription = contentItem.attributes[.firstDescription],
                            case .string(let fdesc) = firstDescription,
                            !fdesc.isEmpty,
                            !contentItem.hasFlag(.isTouched)
                        {
                            // Use first description for untouched items on surfaces
                            surfaceFirstDescriptions.append(fdesc)
                        } else if !contentItem.hasFlag(.isTouched) {
                            // Use generic surface description for touched items without first descriptions
                            if item.hasFlag(.isSurface) {
                                surfaceFirstDescriptions.append(
                                    "On the \(item.name) is \(contentItem.withIndefiniteArticle).")
                            } else {
                                surfaceFirstDescriptions.append(
                                    "The \(item.name) contains \(contentItem.withIndefiniteArticle)."
                                )
                            }
                        }
                    }
                }
            }
        }

        // Now handle the description output
        var descriptionLines: [String] = []

        // First, handle items directly in the location
        let directItems = visibleItems.filter { !$0.hasFlag(.omitDescription) }
        if !directItems.isEmpty {
            // Check if any direct items have firstDescription and haven't been touched
            let hasFirstDescriptions = directItems.contains { item in
                guard
                    let firstDescription = item.attributes[.firstDescription],
                    case .string(let description) = firstDescription,
                    !description.isEmpty
                else {
                    return false
                }
                return !item.hasFlag(.isTouched)
            }

            if hasFirstDescriptions {
                // Use individual first descriptions for untouched direct items
                for item in directItems.sorted() {
                    if let firstDescription = item.attributes[.firstDescription],
                        case .string(let fdesc) = firstDescription,
                        !fdesc.isEmpty,
                        !item.hasFlag(.isTouched)
                    {
                        // Use first description for untouched items
                        descriptionLines.append(fdesc)
                    } else {
                        // Use generic description for touched items or those without first descriptions
                        descriptionLines.append("There is \(item.withIndefiniteArticle) here.")
                    }
                }
            } else {
                // No first descriptions or all items touched - use simple listing
                let itemListing = directItems.listWithIndefiniteArticles
                descriptionLines.append(
                    "There \(directItems.count == 1 ? "is" : "are") \(itemListing) here."
                )
            }
        }

        // Add surface/container first descriptions
        descriptionLines.append(contentsOf: surfaceFirstDescriptions)

        if !descriptionLines.isEmpty {
            description.append(descriptionLines.joined(separator: "\n"))
        }

        return description.joined(separator: "\n\n")
    }
}
