import Foundation

// Parse command line arguments
let arguments = CommandLine.arguments

guard arguments.count >= 4,
      arguments[1] == "--output",
      arguments.contains("--source-files") else {
    print("Usage: IDGeneratorTool --output <path> --source-files <file1> <file2> ...")
    exit(1)
}

let outputPath = arguments[2]
let sourceFileStartIndex = arguments.firstIndex(of: "--source-files")! + 1
let sourceFiles = Array(arguments[sourceFileStartIndex...])

print("🔍 Scanning \(sourceFiles.count) source files for ID patterns...")

// Convert file URLs to file paths if needed
let resolvedSourceFiles = sourceFiles.map { filePath in
    if filePath.hasPrefix("file://") {
        return URL(string: filePath)?.path ?? filePath
    }
    return filePath
}

let resolvedOutputPath = {
    if outputPath.hasPrefix("file://") {
        return URL(string: outputPath)?.path ?? outputPath
    }
    return outputPath
}()

// Scan source files
let discoveredIDs = try scanSourceFiles(resolvedSourceFiles)

print("📝 Discovered \(discoveredIDs.locationIDs.count) LocationIDs and \(discoveredIDs.itemIDs.count) ItemIDs")
print("📝 New LocationIDs: \(discoveredIDs.locationIDs.sorted().joined(separator: ", "))")
print("📝 New ItemIDs: \(discoveredIDs.itemIDs.sorted().joined(separator: ", "))")

// Generate code
let generatedCode = generateIDExtensions(discoveredIDs)

// Write output
try generatedCode.write(toFile: resolvedOutputPath, atomically: true, encoding: .utf8)

print("✅ Generated ID constants written to: \(resolvedOutputPath)")

// MARK: - Discovery

struct DiscoveredIDs {
    let locationIDs: Set<String>
    let itemIDs: Set<String>
}

func scanSourceFiles(_ filePaths: [String]) throws -> DiscoveredIDs {
    var locationIDs = Set<String>()
    var itemIDs = Set<String>()
    var existingLocationIDs = Set<String>()
    var existingItemIDs = Set<String>()
    
    for filePath in filePaths {
        let content = try String(contentsOfFile: filePath, encoding: .utf8)
        
        // First, scan for existing static let declarations to track what's already defined
        let existingLocationMatches = content.matches(of: /static\s+let\s+(\w+)\s*=\s*LocationID/)
        for match in existingLocationMatches {
            existingLocationIDs.insert(String(match.1))
        }
        
        let existingItemMatches = content.matches(of: /static\s+let\s+(\w+)\s*=\s*ItemID/)
        for match in existingItemMatches {
            existingItemIDs.insert(String(match.1))
        }
        
        // Scan for Location(id: .someID, ...) patterns
        let locationUsageMatches = content.matches(of: /Location\s*\(\s*id:\s*\.(\w+)/)
        for match in locationUsageMatches {
            let identifier = String(match.1)
            if !existingLocationIDs.contains(identifier) {
                locationIDs.insert(identifier)
            }
        }
        
        // Scan for Item(id: .someID, ...) patterns  
        let itemUsageMatches = content.matches(of: /Item\s*\(\s*id:\s*\.(\w+)/)
        for match in itemUsageMatches {
            let identifier = String(match.1)
            if !existingItemIDs.contains(identifier) {
                itemIDs.insert(identifier)
            }
        }
        
        // Scan for .to(.someID) patterns in exits
        let exitToMatches = content.matches(of: /\.to\s*\(\s*\.(\w+)\s*\)/)
        for match in exitToMatches {
            let identifier = String(match.1)
            if !existingLocationIDs.contains(identifier) {
                locationIDs.insert(identifier)
            }
        }
        
        // Scan for .location(.someID) patterns in parent entity
        let locationParentMatches = content.matches(of: /\.location\s*\(\s*\.(\w+)\s*\)/)
        for match in locationParentMatches {
            let identifier = String(match.1)
            if !existingLocationIDs.contains(identifier) {
                locationIDs.insert(identifier)
            }
        }
        
        // Scan for .item(.someID) patterns in parent entity
        let itemParentMatches = content.matches(of: /\.item\s*\(\s*\.(\w+)\s*\)/)
        for match in itemParentMatches {
            let identifier = String(match.1)
            if !existingItemIDs.contains(identifier) {
                itemIDs.insert(identifier)
            }
        }
        
        // Scan for Player(in: .someID) patterns
        let playerInMatches = content.matches(of: /Player\s*\(\s*in:\s*\.(\w+)\s*\)/)
        for match in playerInMatches {
            let identifier = String(match.1)
            if !existingLocationIDs.contains(identifier) {
                locationIDs.insert(identifier)
            }
        }
    }
    
    return DiscoveredIDs(locationIDs: locationIDs, itemIDs: itemIDs)
}

// MARK: - Code Generation

func generateIDExtensions(_ discoveredIDs: DiscoveredIDs) -> String {
    var output = [
        "// Generated by IDGeneratorPlugin",
        "// Do not edit this file manually",
        "",
        "import GnustoEngine",
        ""
    ]
    
    // Only generate extensions if there are IDs to add
    if discoveredIDs.locationIDs.isEmpty && discoveredIDs.itemIDs.isEmpty {
        output.append("// No new ID constants need to be generated.")
        output.append("// All discovered IDs are already manually defined.")
        output.append("")
        return output.joined(separator: "\n")
    }
    
    // Generate LocationID extension
    if !discoveredIDs.locationIDs.isEmpty {
        output.append("extension LocationID {")
        
        let sortedLocationIDs = discoveredIDs.locationIDs.sorted()
        for locationID in sortedLocationIDs {
            output.append("    static let \(locationID) = LocationID(\"\(locationID)\")")
        }
        
        output.append("}")
        output.append("")
    }
    
    // Generate ItemID extension
    if !discoveredIDs.itemIDs.isEmpty {
        output.append("extension ItemID {")
        
        let sortedItemIDs = discoveredIDs.itemIDs.sorted()
        for itemID in sortedItemIDs {
            output.append("    static let \(itemID) = ItemID(\"\(itemID)\")")
        }
        
        output.append("}")
        output.append("")
    }
    
    return output.joined(separator: "\n")
} 
