import Foundation

struct CodeGenerator {
    func generate(from gameData: GameData) -> String {
        var output = [
            "// Generated by GnustoAutoWiringPlugin",
            "// Do not edit this file manually",
            "",
            "import GnustoEngine",
            ""
        ]

        // Check if there's anything to generate
        let hasContent = !gameData.locationIDs.isEmpty ||
                         !gameData.itemIDs.isEmpty ||
                         !gameData.globalIDs.isEmpty ||
                         !gameData.fuseIDs.isEmpty ||
                         !gameData.daemonIDs.isEmpty ||
                         !gameData.verbIDs.isEmpty ||
                         !gameData.gameBlueprintTypes.isEmpty

        guard hasContent else {
            output.append("// No ID constants or GameBlueprint extensions need to be generated.")
            output.append("")
            return output.joined(separator: "\n")
        }

        // Generate ID Extensions
        generateIDExtensions(for: gameData, output: &output)

        // Generate GameBlueprint Extensions
        generateGameBlueprintExtensions(for: gameData, output: &output)

        return output.joined(separator: "\n")
    }

    private func generateIDExtensions(for gameData: GameData, output: inout [String]) {
        if !gameData.locationIDs.isEmpty {
            output.append("extension LocationID {")
            for locationID in gameData.locationIDs.sorted() {
                output.append("    static let \(locationID) = LocationID(\"\(locationID)\")")
            }
            output.append("}")
            output.append("")
        }

        if !gameData.itemIDs.isEmpty {
            output.append("extension ItemID {")
            for itemID in gameData.itemIDs.sorted() {
                output.append("    static let \(itemID) = ItemID(\"\(itemID)\")")
            }
            output.append("}")
            output.append("")
        }

        if !gameData.globalIDs.isEmpty {
            output.append("extension GlobalID {")
            for globalID in gameData.globalIDs.sorted() {
                output.append("    static let \(globalID) = GlobalID(\"\(globalID)\")")
            }
            output.append("}")
            output.append("")
        }

        if !gameData.fuseIDs.isEmpty {
            output.append("extension FuseID {")
            for fuseID in gameData.fuseIDs.sorted() {
                output.append("    static let \(fuseID) = FuseID(\"\(fuseID)\")")
            }
            output.append("}")
            output.append("")
        }

        if !gameData.daemonIDs.isEmpty {
            output.append("extension DaemonID {")
            for daemonID in gameData.daemonIDs.sorted() {
                output.append("    static let \(daemonID) = DaemonID(\"\(daemonID)\")")
            }
            output.append("}")
            output.append("")
        }

        if !gameData.verbIDs.isEmpty {
            output.append("extension VerbID {")
            for verbID in gameData.verbIDs.sorted() {
                output.append("    static let \(verbID) = VerbID(\"\(verbID)\")")
            }
            output.append("}")
            output.append("")
        }
    }

    private func generateGameBlueprintExtensions(for gameData: GameData, output: inout [String]) {
        for gameBlueprintType in gameData.gameBlueprintTypes.sorted() {
            var extensionLines: [String] = []

            // Collect all area types that need to be instantiated (for non-static properties)
            var areaInstances: Set<String> = []

            for itemProperty in gameData.items.sorted() {
                if let areaType = gameData.itemToAreaMap[itemProperty] {
                    let isStatic = gameData.propertyIsStatic[itemProperty] ?? true
                    if !isStatic {
                        areaInstances.insert(areaType)
                    }
                }
            }

            for locationProperty in gameData.locations.sorted() {
                if let areaType = gameData.locationToAreaMap[locationProperty] {
                    let isStatic = gameData.propertyIsStatic[locationProperty] ?? true
                    if !isStatic {
                        areaInstances.insert(areaType)
                    }
                }
            }

            // Check for non-static event handlers that need area instances
            for itemHandler in gameData.itemEventHandlers {
                if let areaType = gameData.handlerToAreaMap[itemHandler] {
                    let handlerPropertyName = "\(itemHandler)Handler"
                    let isStatic = gameData.propertyIsStatic[handlerPropertyName] ?? true
                    if !isStatic {
                        areaInstances.insert(areaType)
                    }
                }
            }

            for locationHandler in gameData.locationEventHandlers {
                if let areaType = gameData.handlerToAreaMap[locationHandler] {
                    let handlerPropertyName = "\(locationHandler)Handler"
                    let isStatic = gameData.propertyIsStatic[handlerPropertyName] ?? true
                    if !isStatic {
                        areaInstances.insert(areaType)
                    }
                }
            }

            // Only generate extension if there's content
            if !gameData.items.isEmpty || !gameData.locations.isEmpty || !gameData.itemEventHandlers.isEmpty || !gameData.locationEventHandlers.isEmpty || !gameData.itemComputeHandlers.isEmpty || !gameData.locationComputeHandlers.isEmpty || !gameData.daemonDefinitions.isEmpty || !gameData.fuseDefinitions.isEmpty || hasComputeHandlersToGenerate(gameData) {
                output.append("extension \(gameBlueprintType) {")

                // Generate items property
                if !gameData.items.isEmpty {
                    extensionLines.append("    var items: [Item] {")

                    // Create area instances within this property if needed
                    for areaType in areaInstances.sorted() {
                        extensionLines.append("        let \(areaType.lowercased()) = \(areaType)()")
                    }

                    if !areaInstances.isEmpty {
                        extensionLines.append("")
                    }

                    let returnStatement = areaInstances.isEmpty ? "" : "return "

                    extensionLines.append("        \(returnStatement)[")

                    for itemProperty in gameData.items.sorted() {
                        if let areaType = gameData.itemToAreaMap[itemProperty] {
                            let isStatic = gameData.propertyIsStatic[itemProperty] ?? true
                            if isStatic {
                                extensionLines.append("            \(areaType).\(itemProperty),")
                            } else {
                                extensionLines.append("            \(areaType.lowercased()).\(itemProperty),")
                            }
                        } else {
                            // When area mapping is unknown, skip rather than guessing wrong
                            extensionLines.append("            // \(itemProperty), // Area mapping unknown - please add manually")
                        }
                    }

                    extensionLines.append("        ]")
                    extensionLines.append("    }")
                    extensionLines.append("")
                }

                // Generate locations property
                if !gameData.locations.isEmpty {
                    extensionLines.append("    var locations: [Location] {")

                    // Create area instances within this property if needed
                    for areaType in areaInstances.sorted() {
                        extensionLines.append("        let \(areaType.lowercased()) = \(areaType)()")
                    }

                    if !areaInstances.isEmpty {
                        extensionLines.append("")
                    }

                    let returnStatement = areaInstances.isEmpty ? "" : "return "

                    extensionLines.append("        \(returnStatement)[")

                    for locationProperty in gameData.locations.sorted() {
                        if let areaType = gameData.locationToAreaMap[locationProperty] {
                            let isStatic = gameData.propertyIsStatic[locationProperty] ?? true
                            if isStatic {
                                extensionLines.append("            \(areaType).\(locationProperty),")
                            } else {
                                extensionLines.append("            \(areaType.lowercased()).\(locationProperty),")
                            }
                        } else {
                            // When area mapping is unknown, skip rather than guessing wrong
                            extensionLines.append("            // \(locationProperty), // Area mapping unknown - please add manually")
                        }
                    }

                    extensionLines.append("        ]")
                    extensionLines.append("    }")
                    extensionLines.append("")
                }

                // Generate itemEventHandlers property
                if !gameData.itemEventHandlers.isEmpty {
                    extensionLines.append("    var itemEventHandlers: [ItemID: ItemEventHandler] {")

                    // Create area instances within this property if needed
                    for areaType in areaInstances.sorted() {
                        extensionLines.append("        let \(areaType.lowercased()) = \(areaType)()")
                    }

                    if !areaInstances.isEmpty {
                        extensionLines.append("")
                    }

                    // Check if we have any mapped handlers before generating the return statement
                    let mappedHandlers = gameData.itemEventHandlers.filter { handler in
                        gameData.handlerToAreaMap[handler] != nil
                    }

                    let returnStatement = areaInstances.isEmpty ? "" : "return "

                    if mappedHandlers.isEmpty {
                        extensionLines.append("        \(returnStatement)[:]")
                    } else {
                        extensionLines.append("        \(returnStatement)[")

                        for itemHandler in gameData.itemEventHandlers.sorted() {
                            if let areaType = gameData.handlerToAreaMap[itemHandler] {
                                let handlerPropertyName = "\(itemHandler)Handler"
                                let isStatic = gameData.propertyIsStatic[handlerPropertyName] ?? true
                                if isStatic {
                                    extensionLines.append("            .\(itemHandler): \(areaType).\(handlerPropertyName),")
                                } else {
                                    extensionLines.append("            .\(itemHandler): \(areaType.lowercased()).\(handlerPropertyName),")
                                }
                            } else {
                                extensionLines.append("            // .\(itemHandler): SomeArea.\(itemHandler)Handler, // Area mapping unknown - please add manually")
                            }
                        }

                        extensionLines.append("        ]")
                    }

                    extensionLines.append("    }")
                    extensionLines.append("")
                }

                // Generate locationEventHandlers property
                if !gameData.locationEventHandlers.isEmpty {
                    extensionLines.append("    var locationEventHandlers: [LocationID: LocationEventHandler] {")

                    // Create area instances within this property if needed
                    for areaType in areaInstances.sorted() {
                        extensionLines.append("        let \(areaType.lowercased()) = \(areaType)()")
                    }

                    if !areaInstances.isEmpty {
                        extensionLines.append("")
                    }

                    // Check if we have any mapped handlers before generating the return statement
                    let mappedHandlers = gameData.locationEventHandlers.filter { handler in
                        gameData.handlerToAreaMap[handler] != nil
                    }

                    let returnStatement = areaInstances.isEmpty ? "" : "return "

                    if mappedHandlers.isEmpty {
                        extensionLines.append("        \(returnStatement)[:]")
                    } else {
                        extensionLines.append("        \(returnStatement)[")

                        for locationHandler in gameData.locationEventHandlers.sorted() {
                            if let areaType = gameData.handlerToAreaMap[locationHandler] {
                                let handlerPropertyName = "\(locationHandler)Handler"
                                let isStatic = gameData.propertyIsStatic[handlerPropertyName] ?? true
                                if isStatic {
                                    extensionLines.append("            .\(locationHandler): \(areaType).\(handlerPropertyName),")
                                } else {
                                    extensionLines.append("            .\(locationHandler): \(areaType.lowercased()).\(handlerPropertyName),")
                                }
                            } else {
                                extensionLines.append("            // .\(locationHandler): SomeArea.\(locationHandler)Handler, // Area mapping unknown - please add manually")
                            }
                        }

                        extensionLines.append("        ]")
                    }

                    extensionLines.append("    }")
                    extensionLines.append("")
                }

                // Generate daemons property
                if !gameData.daemonDefinitions.isEmpty {
                    extensionLines.append("    var daemons: [DaemonID: DaemonDefinition] {")

                    // Create area instances within this property if needed
                    for areaType in areaInstances.sorted() {
                        extensionLines.append("        let \(areaType.lowercased()) = \(areaType)()")
                    }

                    if !areaInstances.isEmpty {
                        extensionLines.append("")
                    }

                    // Check if we have any mapped daemon definitions before generating the return statement
                    let mappedDaemons = gameData.daemonDefinitions.filter { daemon in
                        gameData.handlerToAreaMap[daemon] != nil
                    }

                    let returnStatement = areaInstances.isEmpty ? "" : "return "

                    if mappedDaemons.isEmpty {
                        extensionLines.append("        \(returnStatement)[:]")
                    } else {
                        extensionLines.append("        \(returnStatement)[")

                        for daemonProperty in gameData.daemonDefinitions.sorted() {
                            if let areaType = gameData.handlerToAreaMap[daemonProperty] {
                                let isStatic = gameData.propertyIsStatic[daemonProperty] ?? true
                                // Extract daemon ID from property name - convert "swordGlowDaemon" to "swordGlow"
                                let daemonID = daemonProperty.hasSuffix("Daemon") ?
                                    String(daemonProperty.dropLast("Daemon".count)) : daemonProperty

                                if isStatic {
                                    extensionLines.append("            .\(daemonID): \(areaType).\(daemonProperty),")
                                } else {
                                    extensionLines.append("            .\(daemonID): \(areaType.lowercased()).\(daemonProperty),")
                                }
                            } else {
                                extensionLines.append("            // .\(daemonProperty): SomeArea.\(daemonProperty), // Area mapping unknown - please add manually")
                            }
                        }

                        extensionLines.append("        ]")
                    }

                    extensionLines.append("    }")
                    extensionLines.append("")
                }

                // Generate fuses property
                if !gameData.fuseDefinitions.isEmpty {
                    extensionLines.append("    var fuses: [FuseID: FuseDefinition] {")

                    // Create area instances within this property if needed
                    for areaType in areaInstances.sorted() {
                        extensionLines.append("        let \(areaType.lowercased()) = \(areaType)()")
                    }

                    if !areaInstances.isEmpty {
                        extensionLines.append("")
                    }

                    // Check if we have any mapped fuse definitions before generating the return statement
                    let mappedFuses = gameData.fuseDefinitions.filter { fuse in
                        gameData.handlerToAreaMap[fuse] != nil
                    }

                    let returnStatement = areaInstances.isEmpty ? "" : "return "

                    if mappedFuses.isEmpty {
                        extensionLines.append("        \(returnStatement)[:]")
                    } else {
                        extensionLines.append("        \(returnStatement)[")

                        for fuseProperty in gameData.fuseDefinitions.sorted() {
                            if let areaType = gameData.handlerToAreaMap[fuseProperty] {
                                let isStatic = gameData.propertyIsStatic[fuseProperty] ?? true
                                // Extract fuse ID from property name - convert "dynamiteFuse" to "dynamite"
                                let fuseID = fuseProperty.hasSuffix("Fuse") ?
                                    String(fuseProperty.dropLast("Fuse".count)) : fuseProperty

                                if isStatic {
                                    extensionLines.append("            .\(fuseID): \(areaType).\(fuseProperty),")
                                } else {
                                    extensionLines.append("            .\(fuseID): \(areaType.lowercased()).\(fuseProperty),")
                                }
                            } else {
                                extensionLines.append("            // .\(fuseProperty): SomeArea.\(fuseProperty), // Area mapping unknown - please add manually")
                            }
                        }

                        extensionLines.append("        ]")
                    }

                    extensionLines.append("    }")
                    extensionLines.append("")
                }

                                // Generate itemComputers property
                if !gameData.itemComputeHandlers.isEmpty {
                    extensionLines.append("    var itemComputers: [ItemID: ItemComputer] {")

                    // Create area instances within this property if needed
                    for areaType in areaInstances.sorted() {
                        extensionLines.append("        let \(areaType.lowercased()) = \(areaType)()")
                    }

                    if !areaInstances.isEmpty {
                        extensionLines.append("")
                    }

                    // Check if we have any mapped handlers before generating the return statement
                    let mappedHandlers = gameData.itemComputeHandlers.filter { handler in
                        gameData.handlerToAreaMap[handler] != nil
                    }

                    let returnStatement = areaInstances.isEmpty ? "" : "return "

                    if mappedHandlers.isEmpty {
                        extensionLines.append("        \(returnStatement)[:]")
                    } else {
                        extensionLines.append("        \(returnStatement)[")

                        for itemHandler in gameData.itemComputeHandlers.sorted() {
                            if let areaType = gameData.handlerToAreaMap[itemHandler] {
                                let handlerPropertyName = "\(itemHandler)Computer"
                                let isStatic = gameData.propertyIsStatic[handlerPropertyName] ?? true

                                if isStatic {
                                    extensionLines.append("            .\(itemHandler): \(areaType).\(handlerPropertyName),")
                                } else {
                                    extensionLines.append("            .\(itemHandler): \(areaType.lowercased()).\(handlerPropertyName),")
                                }
                            } else {
                                extensionLines.append("            // .\(itemHandler): SomeArea.\(itemHandler)Computer, // Area mapping unknown - please add manually")
                            }
                        }

                        extensionLines.append("        ]")
                    }

                    extensionLines.append("    }")
                    extensionLines.append("")
                } else if hasItemsToGenerate(gameData) {
                    // Generate scaffolding if no compute handlers found but items exist
                    extensionLines.append("    // TODO: Add compute handlers for dynamic item attributes")
                    extensionLines.append("    // Example:")
                    extensionLines.append("    // var itemComputers: [ItemID: ItemComputer] {")
                    extensionLines.append("    //     [")
                    for itemProperty in gameData.items.sorted().prefix(3) {
                        extensionLines.append("    //         .\(extractItemID(from: itemProperty)): ItemComputer { attributeID, gameState in")
                        extensionLines.append("    //             switch attributeID {")
                        extensionLines.append("    //             case .description:")
                        extensionLines.append("    //                 let item = gameState.items[.\(extractItemID(from: itemProperty))]!")
                        extensionLines.append("    //                 return .string(\"Dynamic description for \\(item.name)\")")
                        extensionLines.append("    //             default:")
                        extensionLines.append("    //                 return nil")
                        extensionLines.append("    //             }")
                        extensionLines.append("    //         },")
                    }
                    extensionLines.append("    //     ]")
                    extensionLines.append("    // }")
                    extensionLines.append("")
                }

                                // Generate locationComputers property
                if !gameData.locationComputeHandlers.isEmpty {
                    extensionLines.append("    var locationComputers: [LocationID: LocationComputer] {")

                    // Create area instances within this property if needed
                    for areaType in areaInstances.sorted() {
                        extensionLines.append("        let \(areaType.lowercased()) = \(areaType)()")
                    }

                    if !areaInstances.isEmpty {
                        extensionLines.append("")
                    }

                    // Check if we have any mapped handlers before generating the return statement
                    let mappedHandlers = gameData.locationComputeHandlers.filter { handler in
                        gameData.handlerToAreaMap[handler] != nil
                    }

                    let returnStatement = areaInstances.isEmpty ? "" : "return "

                    if mappedHandlers.isEmpty {
                        extensionLines.append("        \(returnStatement)[:]")
                    } else {
                        extensionLines.append("        \(returnStatement)[")

                        for locationHandler in gameData.locationComputeHandlers.sorted() {
                            if let areaType = gameData.handlerToAreaMap[locationHandler] {
                                let handlerPropertyName = "\(locationHandler)Computer"
                                let isStatic = gameData.propertyIsStatic[handlerPropertyName] ?? true

                                if isStatic {
                                    extensionLines.append("            .\(locationHandler): \(areaType).\(handlerPropertyName),")
                                } else {
                                    extensionLines.append("            .\(locationHandler): \(areaType.lowercased()).\(handlerPropertyName),")
                                }
                            } else {
                                extensionLines.append("            // .\(locationHandler): SomeArea.\(locationHandler)Computer, // Area mapping unknown - please add manually")
                            }
                        }

                        extensionLines.append("        ]")
                    }

                    extensionLines.append("    }")
                    extensionLines.append("")
                } else if hasLocationsToGenerate(gameData) {
                    // Generate scaffolding if no compute handlers found but locations exist
                    extensionLines.append("    // TODO: Add compute handlers for dynamic location attributes")
                    extensionLines.append("    // Example:")
                    extensionLines.append("    // var locationComputers: [LocationID: LocationComputer] {")
                    extensionLines.append("    //     [")
                    for locationProperty in gameData.locations.sorted().prefix(3) {
                        extensionLines.append("    //         .\(extractLocationID(from: locationProperty)): LocationComputer { attributeID, gameState in")
                        extensionLines.append("    //             switch attributeID {")
                        extensionLines.append("    //             case .description:")
                        extensionLines.append("    //                 let location = gameState.locations[.\(extractLocationID(from: locationProperty))]!")
                        extensionLines.append("    //                 return .string(\"Dynamic description for \\(location.name)\")")
                        extensionLines.append("    //             default:")
                        extensionLines.append("    //                 return nil")
                        extensionLines.append("    //             }")
                        extensionLines.append("    //         },")
                    }
                    extensionLines.append("    //     ]")
                    extensionLines.append("    // }")
                    extensionLines.append("")
                }

                output.append(contentsOf: extensionLines)
                output.append("}")
                output.append("")
            }
        }
    }

    // MARK: - Helper methods

    private func hasComputeHandlersToGenerate(_ gameData: GameData) -> Bool {
        return hasItemsToGenerate(gameData) || hasLocationsToGenerate(gameData)
    }

    private func hasItemsToGenerate(_ gameData: GameData) -> Bool {
        return !gameData.items.isEmpty
    }

    private func hasLocationsToGenerate(_ gameData: GameData) -> Bool {
        return !gameData.locations.isEmpty
    }

    private func extractItemID(from propertyName: String) -> String {
        // Try to extract the likely ItemID from the property name
        // e.g., "magicSword" -> "magicSword", "sword" -> "sword"
        return propertyName
    }

    private func extractLocationID(from propertyName: String) -> String {
        // Try to extract the likely LocationID from the property name
        // e.g., "livingRoom" -> "livingRoom", "room" -> "room"
        return propertyName
    }
}
